# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/" # File stored in repository root
    schedule:
      # Check for updates every week at 9am New York time 
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/New_York"
    reviewers: 
      - "Felix-Deng"
      - "matthewlouismueller"
